spring:
  application:
    name: LibraryMS

  messages:
    basename: by/lms/libraryms/i18n/messages
    encoding: UTF-8

  data:
    mongodb:
      uri: mongodb://localhost:27017/librarymsdb

telegram:
  bots:
    libraryMsBot:
      token: 7922300546:AAEhE6e6YgYWmpUbGZPaHYJuEXTSbeSWnks
      name: LibrarymsBot
      commonChannelId: -1002261464282
