spring:
  application:
    name: LibraryMS
    security:
      jwt:
        access-key:
          secret:
            ${JWT_ACCESS_KEY_SECRET}
          expiration-time:
            ${JWT_ACCESS_KEY_EXPIRATION_TIME}
        refresh-key:
          secret:
            ${JWT_REFRESH_KEY_SECRET}
          expiration-time:
            ${JWT_REFRESH_KEY_EXPIRATION_TIME}
      admin:
        urls:
          ${ADMIN_URLS}
      user:
        urls:
          ${USER_URLS}
      reader:
        urls:
          ${READER_URLS}
      librarian:
        urls:
          ${LIBRARIAN_URLS}

  messages:
    basename: by/lms/libraryms/i18n
    encoding: UTF-8

  data:
    mongodb:
      uri: mongodb://localhost:27017/librarymsdb
      auto-index-creation: true

telegram:
  bots:
    libraryMsBot:
      token: 7922300546:AAEhE6e6YgYWmpUbGZPaHYJuEXTSbeSWnks
      name: LibrarymsBot
      commonChannelId: -1002261464282

inventory:
  number:
    firstVal:
      1000
    permissibleError:
      7

aes:
  key:
    path: src/main/resources/aes/aes.key
