spring:
  application:
    name: LibraryMS
    security:
      jwt:
        access-key:
          secret:
            ${JWT_ACCESS_KEY_SECRET}
          expiration-time:
            ${JWT_ACCESS_KEY_EXPIRATION_TIME}
        refresh-key:
          secret:
            ${JWT_REFRESH_KEY_SECRET}
          expiration-time:
            ${JWT_REFRESH_KEY_EXPIRATION_TIME}
      admin:
        urls:
          ${ADMIN_URLS}
      user:
        urls:
          ${USER_URLS}
      reader:
        urls:
          ${READER_URLS}
      librarian:
        urls:
          ${LIBRARIAN_URLS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${LIBRARY_MS_GMAIL_USERNAME}
    password: ${LIBRARY_MS_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    code:
      length: 6

  messages:
    basename: by/lms/libraryms/i18n
    encoding: UTF-8

  data:
    mongodb:
      uri: mongodb://localhost:27017/librarymsdb
      auto-index-creation: true
#Заменить когда добавятся библиотеки
telegram:
  bots:
    libraryMsBot:
      token: 7922300546:AAEhE6e6YgYWmpUbGZPaHYJuEXTSbeSWnks
      name: LibrarymsBot
      commonChannelId: -1002261464282
    libraryMsGroup:
      groupId: -1002652367883
      topics:
        notifications_message_thread_id: 19
        errors_message_thread_id: 17
        book_leading_message_thread_id: 15
        genres_message_thread_id: 13
        authors_message_thread_id: 11
        stock_books_message_thread_id: 2
        readers_message_thread_id: 4
        librarians_message_thread_id: 6
        21s_message_thread_id: 21

inventory:
  number:
    firstVal:
      1000
    permissibleError:
      7

aes:
  key:
    path: src/main/resources/aes/aes.key
